<a href="https://colab.research.google.com/github/Harshada1991/Python_HK/blob/main/Python2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Any library that has binding with C++ is very fast.NumPy has bindings with C++

So NumPy has very fast excution.
Intsll Numpy
pip install numpy

This has NumPy, LIST , ARRAY, RESIZE,RESHAPE,np.array,series, dataframe.
Any library that has binding with C++ is very fast.NumPy has bindings with C++
So NumPy has very fast excution. Intsll Numpy pip install numpy

In [ ]:
List1=[1,2,3,8,6,9]
List1

[1, 2, 3, 8, 6, 9]

In [ ]:
import numpy as np
List1=[1,2,3,8,6,9]
arr1=np.array(List1)
arr1

array([1, 2, 3, 8, 6, 9])

In [ ]:
arr1.size

6

In [ ]:
arr1.shape

(6,)

In [ ]:
import numpy as np
List1=[1,2,3,8,6,9]
List2=[11,22,33,88,66,99]
List3=[100,200,300,800,600,900]

In [ ]:
arr2=np.array([List1,List2,List3])
arr2

array([[  1,   2,   3,   8,   6,   9],
       [ 11,  22,  33,  88,  66,  99],
       [100, 200, 300, 800, 600, 900]])

In [ ]:
import numpy as np
arr3=np.arange(0,10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#2D array
arr2.shape

(3, 6)

In [ ]:
arr2.resize(2,9)
arr2

array([[  1,   2,   3,   8,   6,   9,  11,  22,  33],
       [ 88,  66,  99, 100, 200, 300, 800, 600, 900]])

In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
#reshape creates a new array, while resize modifies the array in place
#resize(): This method modifies the array in-place. It changes the shape of the original array. If the new shape requires more elements than the original array, it will fill the new elements with zeros by default. If the new shape requires fewer elements, it will truncate the array.

arr3=arr2.reshape(6,3)
arr3

array([[  1,   2,   3],
       [  8,   6,   9],
       [ 11,  22,  33],
       [ 88,  66,  99],
       [100, 200, 300],
       [800, 600, 900]])

In [ ]:
list_array1=([[  1,   2,   3],
       [  8,   6,   9],
       [ 11,  22,  33],
       [ 88,  66,  99]])
array1=np.array(list_array1)
array1
print(array1[0:3,1:3])

[[ 2  3]
 [ 6  9]
 [22 33]]


In [ ]:
k=np.ones((2,5),dtype=int)
k

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
k=np.zeros((5),dtype=float)
k

array([0., 0., 0., 0., 0.])

In [ ]:
#creates for this shape from [0,1)
k=np.random.rand(3,3)
k

array([[0.39270494, 0.15214873, 0.68452952],
       [0.7098434 , 0.2918123 , 0.71311433],
       [0.71254566, 0.65003084, 0.27037291]])

In [ ]:
k=np.random.randint(0,10,size=(3,3))
k

array([[8, 3, 5],
       [1, 4, 1],
       [8, 6, 5]])

In [ ]:
k=np.random.randint(0,10,size=(3,3)).reshape(1,9)
k

array([[2, 5, 5, 7, 7, 4, 9, 6, 5]])

In [ ]:
k=np.random.randint(0,100,8).reshape(4,2)
k

array([[57, 26],
       [ 6, 73],
       [13, 47],
       [84, 34]])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a * b
print(result)

[ 4 10 18]


In [ ]:
#arr4= import numpy as np
List1=[1,2,3,8,6,9]
List2=[11,22,33,88,66,99]
List3=[100,200,300,800,600,900]
#List4=["a","b","c"]
List4=[8,9,20,40]

arr5=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

#arr5=np.array([List1,List2[List3[List4]]])
arr5.size

8

In [ ]:
#3D array
arr5=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[5,6],[7,8]]])

In [ ]:
arr5.shape

(3, 2, 2)

PANDAs

In [ ]:
import pandas as pd
#Pandas Series is like a column in a table.
#It is a one-dimensional array holding data of any type.
#Series  have argument as list, set, dictionary. They are values.
#if keys are not mentioned then starts by 0,1...  . Can retrieve series value by index.

df=pd.Series([1,2,33,400,5])
#type(df)=pandas.core.series.Series
#print(df)
#df
print(df.sum)

<bound method Series.sum of 0      1
1      2
2     33
3    400
4      5
dtype: int64>


In [ ]:
ana={"a":0,"b":43,"c":90}
df=pd.Series(a)
df

a     0
b    43
c    90
dtype: int64

In [ ]:
a={"a":0,"b":43,"c":90}
df=pd.Series(a,("a","c"))
df
print(df["c"])

90


In [ ]:
a={"a":0,"b":43,"c":90}
df=pd.Series(a,index=["a","c"])
df

a     0
c    90
dtype: int64

 DATAFRAME is like multi dimensional array/ or table. series was just 1 colum/row, but df is like complete table.
 first argument to be the DATA it will contain. This data can be in various formats, such as a dictionary of Series, a NumPy array, a list of lists, etc.
 Subsequent arguments are typically used for specifying the index and columns, and optionally the** data type (dtype).**

In [ ]:

df=pd.DataFrame([2,3,77,99])
df

0
0   2
1   3
2  77
3  99

In [ ]:
df=pd.DataFrame([[2,3,77,99]],columns=["abc","f","gg","h"])
df

abc  f  gg   h
0    2  3  77  99

In [ ]:
data = {"1":"abc","2":"efg","ert":1}
df=pd.DataFrame(data,index=range(3),columns=["a","b","c"],dtype='str')
df

a    b    c
0  NaN  NaN  NaN
1  NaN  NaN  NaN
2  NaN  NaN  NaN

In [ ]:
#To include the data from your dictionary data in the DataFrame, you need to ensure
# that the column names you specify in the columns argument match the keys in your data dictionary.data = {"1":"abc","2":"efg","ert":1,"f":33}
df=pd.DataFrame(data,index=range(3),columns=["1","2","f"],dtype='str')
df

1    2   f
0  abc  efg  33
1  abc  efg  33
2  abc  efg  33

In [ ]:
#index=[0] i explicitly sets the index of the DataFrame to a list containing a single elemen
#t, 0. This creates a DataFrame with one row and an index of 0.mplies only 1 rowdata = {"1":["abc"], "2":["efg"], "ert":[1]}
data = {"1":["abc"], "2":["efg"], "ert":[1]}
df = pd.DataFrame(data, index=[0])
df

1    2  ert
0  abc  efg    1

In [ ]:
data = {"1":["abc"], "2":["efg"], "ert":[1]}
df = pd.DataFrame(data)
df

1      2  ert
0  [abc]  [efg]  [1]

In [ ]:
data = {"11":"abc","22":"efg","33":1}
df=pd.DataFrame(data,index=range(3),columns=["11","22","33"],dtype='str')
df.to_csv('pythonTocsv.csv')

In [ ]:
!pwd

/content


In [ ]:
ls

pythonTocsv.csv  sample_data/


In [ ]:
cat pythonTocsv.csv

,11,22,33
0,abc,efg,1
1,abc,efg,1
2,abc,efg,1


In [ ]:
#in param give row=1 as key
a=df.loc[1]
df
#print(type(a)) = <class 'numpy.int64'>

<class 'numpy.int64'>


In [ ]:
data = {"11":["abc","def","ghi"],"22":["efg","jkl","mno"],"33":[1,2,3]}
df=pd.DataFrame(data,columns=["11","22","33"],dtype='str')
a=df.iloc[:,:]
a

11   22 33
0  abc  efg  1
1  def  jkl  2
2  ghi  mno  3

In [ ]:
import pandas as pd
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=["col1","col2","col3","col4"])
df.head()

col1  col2  col3  col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [ ]:
df['col2'].value_counts()

col2
1     1
5     1
9     1
13    1
17    1
Name: count, dtype: int64

In [ ]:
a=df.iloc[0:1,0:2]
a
#type(a)=pandas.core.frame.DataFrame

pandas.core.frame.DataFrame

In [ ]:
df.isnull()

11     22     33
0  False  False  False
1  False  False  False
2  False  False  False

In [ ]:
data={"col1":[2,37],"col2":[7,88]}
df=pd.DataFrame(data)
df.sum()

col1    39
col2    95
dtype: int64